FROM node:18-alpine AS base

WORKDIR /app
COPY package*.json ./

# Build
FROM base AS build

RUN npm ci
COPY . .
RUN npm run build

# Prod
FROM base AS prod

ENV NODE_ENV production
RUN npm pkg delete scripts.prepare && npm ci --omit=dev && npm cache clean --force

COPY --from=build /app/build ./build
EXPOSE 8000
CMD ["npm", "start"]



# COPY tsconfig.json ./
