import { IProduct } from '../apps/product/models';

export const sampleProducts: IProduct[] = [
    {
        name: 'Classmate A3 Binded Notebook',
        brand: 'Classmate',
        category: 'Stationary',
        description: 'This is the best Notebook',
        price: 100,
    },
    {
        name: 'Apple iPad Pro',
        brand: 'Apple',
        category: 'Electronics',
        description: 'This is the best Tablet',
        price: 100000,
    },
    {
        name: 'Apple iPhone 14',
        brand: 'Apple',
        category: 'Electronics',
        description: 'This is the best Mobile',
        price: 80000,
    },
    {
        name: 'Apple macBook Pro',
        brand: 'Apple',
        category: 'Electronics',
        description: 'This is the best Laptop',
        price: 150000,
    },
    {
        name: 'Dell Vostro 5568',
        brand: 'Dell',
        category: 'Electronics',
        description: 'This is the best Windows Laptop',
        price: 60000,
    },
    {
        name: 'Luxor Pens',
        brand: 'Luxor',
        category: 'Stationary',
        description: 'This are the best Pens',
        price: 100,
    },
    {
        name: 'Campus Running Shoes',
        brand: 'Campus',
        category: 'Sports',
        description: 'This are the best Shoes',
        price: 2000,
    },
    {
        name: 'GreenSoul Office Chair',
        brand: 'GreenSoul',
        category: 'Furniture',
        description: 'This is the best Chair',
        price: 10000,
    },
    {
        name: 'Apple iPad mini',
        brand: 'Apple',
        category: 'Electronics',
        description: 'This is the best Tablet for Students',
        price: 50000,
    },
    {
        name: 'Apple iMac air',
        brand: 'Apple',
        category: 'Electronics',
        description: 'This is the best Laptop for Students, and moderate usage',
        price: 120000,
    },
    {
        name: 'Apple iStudio',
        brand: 'Apple',
        category: 'Electronics',
        description: 'This is the System for High Performance and Professional',
        price: 200000,
    },
    {
        name: 'Dell Latitude 15',
        brand: 'Dell',
        category: 'Electronics',
        description: 'This is the best Professional Windows Laptop',
        price: 200000,
    },
];
