@host = http://localhost:8000
# @authToken = Bearer {{login.response.body.data.token}}
@authToken = Bearer {{refreshAccessToken.response.body.data.token}}
@refreshToken = {{login.response.body.data.refresh}}

# @todoId = {{getTodos.response.body.data[0]._id}}
@todoId = 641d9d2d436bcc327c18ca73

# -------------------------

# @name invalid-path

GET {{host}}/ HTTP/1.1

###

# @name register

POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
    "email": "ram@test.com",
    "username": "ramtest",
    "password": "Test@123"
}


###

# @name login

POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "rahul@test.com",
    "password": "Test@123"
}

###

# @name refreshAccessToken

POST {{host}}/token/refresh HTTP/1.1
Content-Type: application/json

{
    "refresh": "{{refreshToken}}"
}


###

# @name user

GET {{host}}/users/me HTTP/1.1
Authorization: {{authToken}}

###


###

# @name users

GET {{host}}/users/search/?username=l HTTP/1.1
Authorization: {{authToken}}

###



# @name getTodos

GET {{host}}/todos HTTP/1.1
Authorization: {{authToken}}

###

# @name addTodo

POST {{host}}/todos HTTP/1.1
Authorization: {{authToken}}
Content-Type: application/json

{
    "title": "Todo: 4",
    "detail": "This is Created Using Rest Client VSCode"
}

###

# @name getTodoDetail

GET {{host}}/todos/{{todoId}} HTTP/1.1
Authorization: {{authToken}}

####

# @name updateTodo

PATCH {{host}}/todos/{{todoId}} HTTP/1.1
Authorization: {{authToken}}
Content-Type: application/json

{
    "title": "Todo: 5 Updated",
    "status": "done"
}

###

# @name deleteTodo

DELETE {{host}}/todos/{{todoId}} HTTP/1.1
Authorization: {{authToken}}

###

# @name updatetUserTodoPermissions
PATCH {{host}}/todos/{{todoId}}/users/641d51b0dd51f40d26eaf4db/permissions HTTP/1.1
Authorization: {{authToken}}
Content-Type: application/json

{
    "permissions": ["read", "write"]
}

###

# @name removeUserTodo
DELETE  {{host}}/todos/{{todoId}}/users/641d6d84e3e8626ee0908323/permissions HTTP/1.1
Authorization: {{authToken}}

